### PR TITLE
fix(issue #72): introduce *-with-asm jar which shades ASM and JaCoCo

### PR DESCRIPTION
**Pull request by famod**
#### Short description of what this resolves:

Introduces an alternate `arquillian-jacoco-with-asm` jarfile that includes "private" ASM and JaCoCo packages that do not clash with (older) server-side ASM.

~~ℹ️ This is currently in WIP/draft state. I will add some code remarks myself. Feedback very much appreciated!~~

#### Changes proposed in this pull request:

- turn project into multi-module project, retaining `arquillian-jacoco` as is to avoid regressions for users who don't want/need to use the new `with-asm` alternative.
- introduce `arquillian-jacoco-with-asm` module that takes `arquillian-jacoco` and "relocates" all ASM (and thus also JaCoCo) packages to `org.jboss.arquillian.extension.jacoco.org.[...]` via `maven-shade-plugin`
- small offtopic improvement: skip extraction of test JBoss when `-Dmaven.test.skip[=true]`

**Fixes**: #72 and probably #25

### CODE REVIEW

**Comment by famod** [comment]
Note: I am going to leave regular comments for topics that are not suitable to be added to certain code lines.

**Comment by famod** [comment]
Q: **First, why the multi-module approach?**
A: `maven-shade-plugin` (let's call it MSP as I will have to repeat that often here) does not really support `provided` scope dependencies ([MSHADE-181](https://issues.apache.org/jira/browse/MSHADE-181)) but `jacoco-core` has exactly that scope (which I didn't question).
So just calling MSP in the previous "single-module" project wouldn't have worked (without touching the scope).
Furthermore, even though you _can_ produce a secondary attached shaded artifact with MSP, you can only have one POM. That POM would still declare all dependencies, although `jacoco-core` would already be "included" in the secondary  artifact. I think that would confuse the users.

**Comment by famod** [comment]
Q: **Why are all non-test dependencies defined in the parent POM?**
A: Since `provided` dependencies are _not_ inherited and since I wanted MSP to retain all the non-shaded dependencies in the "dependency reduced POM" I had to declare them in the parent in order to avoid repeating them in `with-asm`.

**Comment by famod** [comment]
One last thing for now: I would like to extend `README.asciidoc` describing this new `with-asm` flavor.
Is this ok or should such documentation go elsewehre?

**Comment by famod** [comment]
@bartoszmajsak Feedback is very much appreciated!

**Comment by famod** [comment]
> Can you list pending work that keeps this PR in a draft state?

Sure. Main points:
- `maven-shade-plugin` 3.2.2 has not yet been released. I will try to "ping" the maven-dev list again.
- Unclear testing approach. Extracting a common test module which can be used for both flavours (different JaCoCo and ASM packages!) seems rather complex.
The simple solution would be to ignore this for now and add a full-fledged testing approach for `with-asm` later, whenever this will be.
- Decide what to to with those `MANIFEST.MF` files. We might want to simply skip them all and just include our own (generated one?).

The rest (Readme & removal of `module-info`) I will add in the next few days, tomorrow hopefully.

**Comment by famod** [comment]
I resolved all of the remaining points _except_ MSP 3.2.2 (still waiting for that) and the testing challenge (skip for now?).

**Comment by famod** [comment]
I am a little tired of waiting for `maven-shade-plugin` 3.2.2 to be relased so I switched to a specific snapshot version that includes MSHADE-311.
I am not sure whether this is acceptable for a limited amount of time. I'd create another PR as soon as 3.2.2 is released.

As for the testing challenge: I simply don't have the time right now to look into that. IMHO this is something that can be added later.

**Comment by bartoszmajsak** [comment]
Thanks a lot, @famod. Can we ping someone wrt to the release timeline for `maven-shade-plugin`. Personally I'm totally fine using SNAPSHOT myself, but I can imagine this can scare some people off :)

**Comment by famod** [comment]
> Can we ping someone wrt to the release timeline for maven-shade-plugin

I tried twice: https://lists.apache.org/x/thread.html/2258bb598c3b173ef5228776aa1e3021c4dc323751f328e897b1aa50@%3Cdev.maven.apache.org%3E

Both times someone answered the call and something was committed, but a release is yet to been seen.

> Personally I'm totally fine using SNAPSHOT myself, but I can imagine this can scare some people off :)

It's only used internally, not "propagated" as a dependency, so...

**Comment by bartoszmajsak** [comment]
> It's only used internally, not "propagated" as a dependency, so...

Sure, but it is also a moving target :) Potentially can break everything with one innocent change on their side. I will join the thread to see if we can get some traction.

**Comment by famod** [comment]
> Potentially can break everything with one innocent change on their side.

Since it is a concrete snapshot version, only deletion of that version from the snapshot repo would be a problem.
But right, that can also happen without a warning.

**Comment by famod** [comment]
FYI, voting for releasing MSP 3.2.2 has begun: https://lists.apache.org/thread.html/r86a13a941eacf9580fbeef414efc1b5622c4af9d4cf715e5d8fcdd96%40%3Cdev.maven.apache.org%3E

**Comment by famod** [comment]
@bartoszmajsak I replaced MSP 3.2.2-SNAPSHOT with 3.2.2 final that was released today.

**This PR should now be ready to merge!**

**Pull request merged**
